name: 文章CMS
identification: notadd/content
description: 'Notadd 内容管理模块'
author:
    - Notadd
    - notadd@ibenchu.com
version: 2.0.0
assets:
    administration:
        notadd/content:
            permissions: ''
            scripts: assets/content/administration/js/module.min.js
            stylesheets: assets/content/administration/css/module.min.css
csrf:
    - 'api/article*'
    - 'api/category*'
    - 'api/content*'
    - 'api/page*'
entry: '/content'
events:
    subscribes:
        - Notadd\Content\Listeners\RouteRegister
migrations:
    - databases/migrations
permissions:
    -
        description: 内容管理权限。
        groups:
            -
                description: 内容管理权限定义。
                identification: content
                name: 内容管理权限
        identification: content
        name: 内容管理
publishes:
    assets/content/administration: resources/mixes/administration/dist/assets/content/administration
    assets/content/foreground: resources/mixes/foreground/dist/assets/content/foreground
settings:
    content.seo.article.description: ''
    content.seo.article.keyword: ''
    content.seo.article.title: ''
    content.seo.category.description: ''
    content.seo.category.keyword: ''
    content.seo.category.title: ''
    content.seo.page.description: ''
    content.seo.page.keyword: ''
    content.seo.page.title: ''
